services:
  hacklab:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: hacklab
    ports:
      - "2222:22"  # Expose SSH port
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - type: bind
        source: .data
        target: /data
        bind:
          create_host_path: true
      - type: volume
        source: root
        target: /root   # Ensure the /root volume persists
        volume:
          nocopy: true  # Prevent Docker from copying files from /root into the volume
    environment:
      - "SSHD_PORT=2222"  # Optional: Define environment variable for SSH port

volumes:
  root:
